# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6920d13b615d10c285e494b833691eefc67fe4286b1afa87e4dc50730254f6eed3884620d6fee7dc612aa92e651400e163ca6e47338253cece11a9048f7954a

test:
  secret_key_base: fc93df0d65684b1a4e06d7d49c9c46e09b44a04a980a0fdca47985f0db8d431f6a9fa864bcf7492c942f31c29c7d09cbe29b4a33d35c927af63dd4093a395cdf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
